# Lista de productos de interes para las queries al endpoint de Precios Claros.
#
# Copiada de PRODUCT_MAP en lista-super/index.html (el diccionario de la app
# para reconocer/categorizar items que el usuario escribe en su lista). No se
# sincroniza automaticamente -- si ese diccionario crece con productos nuevos
# que valga la pena tambien buscar en Precios Claros, copiar las claves nuevas
# aca a mano.

PRODUCTOS_INTERES = [
    "manzana",
    "banana",
    "platano",
    "naranja",
    "mandarina",
    "limon",
    "pomelo",
    "pera",
    "uva",
    "frutilla",
    "durazno",
    "ciruela",
    "kiwi",
    "ananá",
    "ananas",
    "melon",
    "sandia",
    "palta",
    "mango",
    "cereza",
    "papa",
    "batata",
    "cebolla",
    "tomate",
    "lechuga",
    "zanahoria",
    "zapallo",
    "zapallito",
    "calabaza",
    "morron",
    "pimiento",
    "ajo",
    "apio",
    "brocoli",
    "coliflor",
    "espinaca",
    "acelga",
    "repollo",
    "pepino",
    "berenjena",
    "choclo",
    "remolacha",
    "rabanito",
    "perejil",
    "cilantro",
    "albahaca",
    "jengibre",
    "hongos",
    "champiñones",
    "champignones",
    "puerro",
    "chaucha",
    "arveja",
    "arvejas frescas",
    "carne",
    "carne picada",
    "asado",
    "vacio",
    "matambre",
    "bife",
    "bife de chorizo",
    "lomo",
    "pollo",
    "pechuga",
    "pata muslo",
    "milanesa",
    "cerdo",
    "chorizo",
    "salchicha",
    "morcilla",
    "panceta",
    "costilla",
    "costeleta",
    "jamon",
    "jamon cocido",
    "jamon crudo",
    "salame",
    "salamin",
    "mortadela",
    "paleta",
    "bondiola",
    "higado",
    "nalga",
    "peceto",
    "cuadril",
    "entraña",
    "tapa de asado",
    "hamburguesa",
    "pate",
    "fiambre",
    "queso de cerdo",
    "pescado",
    "merluza",
    "salmon",
    "atun",
    "atun lata",
    "camaron",
    "langostino",
    "mejillon",
    "calamar",
    "pulpo",
    "trucha",
    "anchoa",
    "caballa",
    "sardina",
    "leche",
    "yogur",
    "yogurt",
    "queso",
    "queso rallado",
    "queso cremoso",
    "queso untable",
    "muzzarella",
    "mozzarella",
    "manteca",
    "crema",
    "crema de leche",
    "huevo",
    "dulce de leche",
    "ricota",
    "flan",
    "postre",
    "danonino",
    "yogur bebible",
    "leche chocolatada",
    "crema chantilly",
    "margarina",
    "pan",
    "pan lactal",
    "pan de molde",
    "pan frances",
    "factura",
    "medialuna",
    "tostadas",
    "tostado",
    "bizcocho",
    "grisines",
    "pan rallado",
    "pan dulce",
    "torta",
    "masitas",
    "magdalenas",
    "budin",
    "pan arabe",
    "tapas de empanada",
    "tapas de tarta",
    "prepizza",
    "arroz",
    "fideos",
    "pasta",
    "polenta",
    "harina",
    "harina 0000",
    "harina leudante",
    "azucar",
    "sal",
    "yerba",
    "yerba mate",
    "cafe",
    "te",
    "mate cocido",
    "aceite",
    "vinagre",
    "lenteja",
    "garbanzo",
    "poroto",
    "tomate lata",
    "pure de tomate",
    "salsa de tomate",
    "caldo",
    "caldo en cubos",
    "gelatina",
    "avena",
    "cereal",
    "miel",
    "mermelada",
    "aceitunas",
    "choclo lata",
    "arveja lata",
    "levadura",
    "bicarbonato",
    "maicena",
    "fecula de maiz",
    "tostadas de arroz",
    "sopa",
    "sopa instantanea",
    "choclo en lata",
    "mayonesa",
    "ketchup",
    "mostaza",
    "salsa golf",
    "aji molido",
    "oregano",
    "pimienta",
    "comino",
    "laurel",
    "nuez moscada",
    "curry",
    "pimenton",
    "salsa soja",
    "soja",
    "salsa de soja",
    "tabasco",
    "aderezo",
    "provenzal",
    "condimento",
    "sal de ajo",
    "canela",
    "vainilla",
    "agua",
    "agua mineral",
    "agua con gas",
    "soda",
    "gaseosa",
    "coca cola",
    "coca",
    "sprite",
    "fanta",
    "jugo",
    "jugo exprimido",
    "jugo en polvo",
    "cerveza",
    "vino",
    "fernet",
    "whisky",
    "vodka",
    "gin",
    "champagne",
    "sidra",
    "energizante",
    "isotonica",
    "gatorade",
    "tonica",
    "helado",
    "papas fritas congeladas",
    "verdura congelada",
    "nuggets",
    "rebozados",
    "tarta congelada",
    "pizza congelada",
    "medallon",
    "empanadas congeladas",
    "hielo",
    "galletitas",
    "galletas",
    "papas fritas",
    "papas lays",
    "chizitos",
    "chocolate",
    "alfajor",
    "caramelos",
    "chicles",
    "turron",
    "maní",
    "mani",
    "frutos secos",
    "pasas de uva",
    "palitos salados",
    "conitos",
    "barrita de cereal",
    "budin ingles",
    "vainillas",
    "oblea",
    "bombones",
    "galletitas de agua",
    "lavandina",
    "detergente",
    "jabon en polvo",
    "suavizante",
    "esponja",
    "trapo de piso",
    "rollo de cocina",
    "servilletas",
    "bolsas de residuo",
    "limpiavidrios",
    "desengrasante",
    "lustramuebles",
    "insecticida",
    "ambientador",
    "jabon liquido",
    "jabon para platos",
    "guantes de latex",
    "fibra",
    "trapo rejilla",
    "pastilla para inodoro",
    "aromatizante",
    "shampoo",
    "champu",
    "acondicionador",
    "jabon de tocador",
    "pasta dental",
    "crema dental",
    "cepillo de dientes",
    "hilo dental",
    "desodorante",
    "protector solar",
    "crema corporal",
    "crema de manos",
    "algodon",
    "hisopos",
    "toallitas humedas",
    "toallas femeninas",
    "tampones",
    "papel higienico",
    "maquinita de afeitar",
    "afeitadora",
    "espuma de afeitar",
    "perfume",
    "colonia",
    "protector diario",
    "preservativos",
    "curitas",
    "alcohol en gel",
    "pañales",
    "panales",
    "leche en polvo bebe",
    "toallitas bebe",
    "papilla",
    "compota",
    "crema para pañales",
    "chupete",
    "mamadera",
    "alimento para perro",
    "alimento para gato",
    "balanceado",
    "arena para gato",
    "snacks para perro",
    "snacks para gato",
]
